name: grocery_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.18
  package_info_plus: ^3.0.3
  google_fonts: ^4.0.3
  glassmorphism: ^3.0.0
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  animations: ^2.0.7
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/splash.png"    
  min_sdk_android: 21
    

